INSERT INTO "public"."collections" ("id", "work_id", "collection_name", "year", "tags", "synopsis", "description", "image_name", "image_name1", "image_name2", "image_name3", "image_name4", "title1", "image_name5", "image_name6", "image_name7", "image_name8", "image_name9", "folder", "image_name41", "title11", "image_name_title", "image_name1_title", "image_name2_title", "image_name3_title", "image_name4_title", "image_name5_title", "image_name6_title", "image_name7_title", "image_name8_title", "image_name9_title", "image_name41_title") VALUES ('2', '2', 'Automotive', '2025', '{"Photography","Automotive","Personal"}', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'The Canadian International AutoShow (CIAS) is Canada's largest auto show. This event has been held in Toronto, Ontario, since 1974 and is staged annually in February at the Metro Toronto Convention Centre. It draws an average of 300,000 visitors throughout its showing from Ontario and Western New York.[1]The Canadian International AutoShow (CIAS) is Canada's largest auto show. This event has been held in Toronto, Ontario, since 1974 and is staged annually in February at the Metro Toronto Convention Centre. It draws an average of 300,000 visitors throughout its showing from Ontario and Western New York. - база даних (titel description )
', 'image_hero.png', 'image1.png', 'image2.png', 'image3.png', 'image9.png', 'Racing against what may be
the stiffest competition', 'image5.png', 'image6.png', 'image7.png', 'image8.png', 'image6.png', 'personal', 'image9.png', 'Racing against what may be
the stiffest competition', 'Automotive - Main Image', 'Automotive - Photo 1', 'Automotive - Photo 2', 'Automotive - Photo 3', 'Racing against what may be
the stiffest competition - Detail', 'Automotive - Detail 1', 'Automotive - Detail 2', 'Automotive - Detail 3', 'Automotive - Detail 4', 'Automotive - Additional View', 'Racing against what may be
the stiffest competition - Alternative View'), ('3', '3', 'Portrait', '2025', '{"People","Emotions","Studio"}', 'Human emotions', 'Expressive portrait photography series.', 'image_hero.png', 'image1.png', 'image2.png', 'image3.png', 'image9.png', 'Faces and stories', 'image5.png', 'image6.png', 'image7.png', 'image8.png', 'image8.png', 'commercial', 'image9.png', 'Faces and stories', 'Portrait - Main Image', 'Portrait - Photo 1', 'Portrait - Photo 2', 'Portrait - Photo 3', 'Faces and stories - Detail', 'Portrait - Detail 1', 'Portrait - Detail 2', 'Portrait - Detail 3', 'Portrait - Detail 4', 'Portrait - Additional View', 'Faces and stories - Alternative View'), ('4', '4', 'Abstract', '2024', '{"Art","Experimental","Colors"}', 'Abstract visions', 'Creative abstract compositions.', 'image_hero.png', 'image1.png', 'image2.png', 'image3.png', 'image9.png', 'Beyond reality', 'image5.png', 'image6.png', 'image7.png', 'image8.png', 'image6.png', 'commercial', 'image9.png', 'Beyond reality', 'Abstract - Main Image', 'Abstract - Photo 1', 'Abstract - Photo 2', 'Abstract - Photo 3', 'Beyond reality - Detail', 'Abstract - Detail 1', 'Abstract - Detail 2', 'Abstract - Detail 3', 'Abstract - Detail 4', 'Abstract - Additional View', 'Beyond reality - Alternative View'), ('5', '5', 'Documentary', '2023', '{"Journalism","Storytelling","Real-life"}', 'Real stories', 'Documentary photography projects.', 'image_hero.png', 'image1.png', 'image2.png', 'image3.png', 'image9.png', 'Life unfiltered', 'image5.png', 'image6.png', 'image7.png', 'image8.png', 'image6.png', 'commercial', 'image9.png', 'Racing against what may be
the stiffest competition', 'Documentary - Main Image', 'Documentary - Photo 1', 'Documentary - Photo 2', 'Documentary - Photo 3', 'Life unfiltered - Detail', 'Documentary - Detail 1', 'Documentary - Detail 2', 'Documentary - Detail 3', 'Documentary - Detail 4', 'Documentary - Additional View', 'Racing against what may be
the stiffest competition - Alternative View'), ('6', '6', 'Fashion', '2025', '{"Style","Design","Trends"}', 'Fashion world', 'Editorial fashion photography.', 'image_hero.png', 'image1.png', 'image2.png', 'image3.png', 'image9.png', 'Style statements', 'image5.png', 'image6.png', 'image7.png', 'image8.png', 'image6.png', 'personal', 'image9.png', 'Racing against what may be
the stiffest competition', 'Fashion - Main Image', 'Fashion - Photo 1', 'Fashion - Photo 2', 'Fashion - Photo 3', 'Style statements - Detail', 'Fashion - Detail 1', 'Fashion - Detail 2', 'Fashion - Detail 3', 'Fashion - Detail 4', 'Fashion - Additional View', 'Racing against what may be
the stiffest competition - Alternative View'), ('7', '7', 'Food', '2024', '{"Culinary","Culture","Art"}', 'Culinary art', 'Artistic food photography.', 'image_hero.png', 'image1.png', 'image2.png', 'image3.png', 'image9.png', 'Taste the moment', 'image5.png', 'image6.png', 'image7.png', 'image8.png', 'image6.png', 'personal', 'image9.png', 'Racing against what may be
the stiffest competition', 'Food - Main Image', 'Food - Photo 1', 'Food - Photo 2', 'Food - Photo 3', 'Taste the moment - Detail', 'Food - Detail 1', 'Food - Detail 2', 'Food - Detail 3', 'Food - Detail 4', 'Food - Additional View', 'Racing against what may be
the stiffest competition - Alternative View'), ('8', '8', 'Travel', '2023', '{"Adventure","Landscapes","Culture"}', 'Travel diaries', 'Journeys around the world.', 'image_hero.png', 'image1.png', 'image2.png', 'image3.png', 'image9.png', 'Wanderlust', 'image5.png', 'image6.png', 'image7.png', 'image8.png', 'image6.png', 'personal', 'image9.png', 'Racing against what may be
the stiffest competition', 'Travel - Main Image', 'Travel - Photo 1', 'Travel - Photo 2', 'Travel - Photo 3', 'Wanderlust - Detail', 'Travel - Detail 1', 'Travel - Detail 2', 'Travel - Detail 3', 'Travel - Detail 4', 'Travel - Additional View', 'Racing against what may be
the stiffest competition - Alternative View'), ('9', '9', 'B&W', '2025', '{"Monochrome","Timeless","Classic"}', 'Black & white', 'Classic monochrome photography.', 'image_hero.png', 'image1.png', '', 'image3.png', 'image9.png', 'Shades of gray', 'image5.png', 'image6.png', 'image7.png', 'image8.png', 'image6.png', 'personal', '', '', 'B&W - Main Image', 'B&W - Photo 1', 'B&W - Photo 2', 'B&W - Photo 3', 'Shades of gray - Detail', 'B&W - Detail 1', 'B&W - Detail 2', 'B&W - Detail 3', 'B&W - Detail 4', 'B&W - Additional View', ' - Alternative View'), ('10', '10', 'Street', '2023', '{"Urban","Candid","Life"}', 'Street moments', 'Candid street photography.', 'image_hero.png', 'image1.png', 'image2.png', 'image3.png', 'image9.png', 'Urban tales', 'image5.png', 'image6.png', 'image7.png', 'image8.png', 'image6.png', 'personal', 'image9.png', 'Racing against what may be
the stiffest competition', 'Street - Main Image', 'Street - Photo 1', 'Street - Photo 2', 'Street - Photo 3', 'Urban tales - Detail', 'Street - Detail 1', 'Street - Detail 2', 'Street - Detail 3', 'Street - Detail 4', 'Street - Additional View', 'Racing against what may be
the stiffest competition - Alternative View'), ('11', '11', 'B&W', '2025', '{"Monochrome","Timeless","Classic"}', 'Black & white', 'Classic monochrome photography.', 'image_hero.png', 'image1.png', 'image2.png', 'image3.png', 'image9.png', 'Shades of gray', 'image5.png', 'image6.png', 'image7.png', 'image8.png', 'image6.png', 'commercial', 'image9.png', 'Racing against what may be
the stiffest competition', 'B&W - Main Image', 'B&W - Photo 1', 'B&W - Photo 2', 'B&W - Photo 3', 'Shades of gray - Detail', 'B&W - Detail 1', 'B&W - Detail 2', 'B&W - Detail 3', 'B&W - Detail 4', 'B&W - Additional View', 'Racing against what may be
the stiffest competition - Alternative View'), ('12', '12', 'Street', '2023', '{"Urban","Candid","Life"}', 'Street moments', 'Candid street photography.', 'image_hero.png', 'image1.png', 'image2.png', 'image3.png', 'image9.png', 'Urban tales', 'image5.png', 'image6.png', 'image7.png', 'image8.png', 'image6.png', 'commercial', 'image9.png', 'Racing against what may be
the stiffest competition', 'Street - Main Image', 'Street - Photo 1', 'Street - Photo 2', 'Street - Photo 3', 'Urban tales - Detail', 'Street - Detail 1', 'Street - Detail 2', 'Street - Detail 3', 'Street - Detail 4', 'Street - Additional View', 'Racing against what may be
the stiffest competition - Alternative View');